apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: kube-demo-app
build:
  local:
    push: false           # <--- DON'T TRY TO PUSH TO INTERNET
  artifacts:
    - image: nerdsteyn/kube-demo-app
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - deployment.yaml
    - service.yaml
deploy:
  kubectl: {}
portForward:
  - resourceType: service
    resourceName: demo-service
    port: 80
    localPort: 8080
